/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tugas_akhir_penjualanbarangelektronik;

import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author LENOVO
 */
public class laporan extends javax.swing.JFrame {
    private String dataProduk;
    /**
     * Creates new form tabbed_pane
     */
    public laporan(String data) {
        initComponents();
        tabbedPane.addTab("Data Produk Baru", new JScrollPane(new JTextArea(data)));
    }
    public void produk1(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        tabbedPane = new javax.swing.JTabbedPane();
        pn_penjualan = new javax.swing.JPanel();
        btntampilkan = new javax.swing.JButton();
        btnhapus = new javax.swing.JButton();
        sp_penjualan = new javax.swing.JScrollPane();
        table_penjualan = new javax.swing.JTable();
        pn_invoice = new javax.swing.JPanel();
        sp_laporan = new javax.swing.JScrollPane();
        txa_laporan = new javax.swing.JTextArea();
        btntampilkaninvoice = new javax.swing.JButton();
        btnhapusinvoice = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btntampilkan.setText("Tampilkan data ");
        btntampilkan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampilkanActionPerformed(evt);
            }
        });

        btnhapus.setText("Hapus");

        table_penjualan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nama Produk", "Jumlah", "Harga PerUnit (Rp)", "Total (Rp)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        sp_penjualan.setViewportView(table_penjualan);

        javax.swing.GroupLayout pn_penjualanLayout = new javax.swing.GroupLayout(pn_penjualan);
        pn_penjualan.setLayout(pn_penjualanLayout);
        pn_penjualanLayout.setHorizontalGroup(
            pn_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sp_penjualan)
            .addGroup(pn_penjualanLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(btntampilkan)
                .addGap(179, 179, 179)
                .addComponent(btnhapus)
                .addContainerGap(461, Short.MAX_VALUE))
        );
        pn_penjualanLayout.setVerticalGroup(
            pn_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_penjualanLayout.createSequentialGroup()
                .addComponent(sp_penjualan, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(pn_penjualanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntampilkan)
                    .addComponent(btnhapus))
                .addGap(0, 142, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Penjualan", pn_penjualan);

        txa_laporan.setColumns(20);
        txa_laporan.setRows(5);
        sp_laporan.setViewportView(txa_laporan);

        btntampilkaninvoice.setText("Tampilkan");
        btntampilkaninvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntampilkaninvoiceActionPerformed(evt);
            }
        });

        btnhapusinvoice.setText("Hapus");
        btnhapusinvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhapusinvoiceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pn_invoiceLayout = new javax.swing.GroupLayout(pn_invoice);
        pn_invoice.setLayout(pn_invoiceLayout);
        pn_invoiceLayout.setHorizontalGroup(
            pn_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_invoiceLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btntampilkaninvoice)
                .addGap(199, 199, 199)
                .addComponent(btnhapusinvoice)
                .addContainerGap(478, Short.MAX_VALUE))
            .addComponent(sp_laporan)
        );
        pn_invoiceLayout.setVerticalGroup(
            pn_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pn_invoiceLayout.createSequentialGroup()
                .addComponent(sp_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pn_invoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntampilkaninvoice)
                    .addComponent(btnhapusinvoice))
                .addGap(0, 70, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Invoice/Laporan", pn_invoice);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabbedPane)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btntampilkaninvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampilkaninvoiceActionPerformed
       if (table_penjualan.getRowCount() == 0) {
            
       StringBuilder invoice = new StringBuilder();
        invoice.append("----- INVOICE PENJUALAN -----\n");
        invoice.append("Tanggal: ").append(new SimpleDateFormat("dd/MM/yyyy HH:mm:ss").format(new Date())).append("\n\n");

        invoice.append(String.format("%-20s %10s %15s %15s\n", "Produk", "Jumlah", "Harga/Unit (Rp)", "Total (Rp)"));
        invoice.append("-----------------------------------------------------------------\n");
        
        double grandTotal = 0;
        for (int i = 0; i < table_penjualan.getRowCount(); i++) {
            String product = table_penjualan.getValueAt(i, 0).toString();
            String qty = table_penjualan.getValueAt(i, 1).toString();
            String price = table_penjualan.getValueAt(i, 2).toString();
            String total = table_penjualan.getValueAt(i, 3).toString();

            invoice.append(String.format("%-20s %10s %15s %15s\n", product, qty, price, total));
         grandTotal += Double.parseDouble(total.replaceAll(",", ""));
        }

        invoice.append("-----------------------------------------------------------------\n");
        invoice.append(String.format("%-20s %10s %15s %15s\n", "", "", "Grand Total:", String.format("%,.2f", grandTotal)));

        txa_laporan.setText(invoice.toString());
        tabbedPane.setSelectedIndex(1); // Switch to Invoice tab
       }else{
           JOptionPane.showMessageDialog(this, "Daftar penjualan kosong. Tambahkan penjualan terlebih dahulu.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
       
            return;
       }
    }//GEN-LAST:event_btntampilkaninvoiceActionPerformed

    private void btnhapusinvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhapusinvoiceActionPerformed
       txa_laporan.setText("");
    }//GEN-LAST:event_btnhapusinvoiceActionPerformed

    private void btntampilkanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntampilkanActionPerformed
     produk pk = new produk();
      pk.setVisible(true);
    }//GEN-LAST:event_btntampilkanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(laporan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new laporan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhapus;
    private javax.swing.JButton btnhapusinvoice;
    private javax.swing.JButton btntampilkan;
    private javax.swing.JButton btntampilkaninvoice;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel pn_invoice;
    private javax.swing.JPanel pn_penjualan;
    private javax.swing.JScrollPane sp_laporan;
    private javax.swing.JScrollPane sp_penjualan;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTable table_penjualan;
    private javax.swing.JTextArea txa_laporan;
    // End of variables declaration//GEN-END:variables
}
